/*
 * generated by Xtext 2.10.0
 */
package ingraph.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class CypherScopeProvider extends AbstractCypherScopeProvider {

}
