language: java
jdk:
  - oraclejdk8
install: false
script:
  - ./gradlew assemble
  - ./gradlew check -x test --continue
notifications:
  slack: bme-db-lab:egojac3QB9DyjtDvzHiNIaqo
  email: false
  on_success: change
  on_failure: always
