language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
    - texlive-base
    - texlive-science
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
install: false
script:
  - ./gradlew assemble
  - ./gradlew check -x test --continue
  - cd opencypher-report
  - make
notifications:
  slack: bme-db-lab:egojac3QB9DyjtDvzHiNIaqo
  email: false
  on_success: change
  on_failure: always
