(ns ingraph.sre.cost)

(defn ??? [] throw (Exception. "Not implemented yet"))

(defweight GetVertices [op constr-lkp state] (???))
(defweight GetVerticesByLabels [op constr-lkp state] (???))
(defweight CheckLabels [op constr-lkp state] (???))
(defweight GetEdges [op constr-lkp state] (???))
(defweight GetEdgesByType [op constr-lkp state] (???))
(defweight CheckType [op constr-lkp state] (???))
(defweight ExtendOut [op constr-lkp state] (???))
(defweight ExtendIn [op constr-lkp state] (???))
(defweight ExtendOutByType [op constr-lkp state] (???))
(defweight ExtendInByType [op constr-lkp state] (???))
(defweight Join [op constr-lkp state] (???))
(defweight JoinByType [op constr-lkp state] (???))
(defweight CheckDirectedEdge [op constr-lkp state] (???))
(defweight CheckDiresctedEdgeByType [op constr-lkp state] (???))
(defweight EvalEquals [op constr-lkp state] (???))
