/**
 * generated by Xtext 2.10.0
 */
package ingraph.report.featuregrammar.feature;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Background</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ingraph.report.featuregrammar.feature.FeaturePackage#getBackground()
 * @model
 * @generated
 */
public interface Background extends AbstractScenario
{
} // Background
