/*
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.opencypher.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class OpenCypherAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/slizaa/neo4j/opencypher/parser/antlr/internal/InternalOpenCypherParser.tokens");
	}
}
