<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="openCypher" nsURI="http://www.slizaa.org/neo4j/opencypher/OpenCypher"
    nsPrefix="openCypher">
  <eClassifiers xsi:type="ecore:EClass" name="Cypher">
    <eStructuralFeatures xsi:type="ecore:EReference" name="queryOptions" eType="#//QueryOptions"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="#//Statement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueryOptions"/>
  <eClassifiers xsi:type="ecore:EClass" name="CypherOption">
    <eStructuralFeatures xsi:type="ecore:EReference" name="versionNumber" eType="#//VersionNumber"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configurationOption" upperBound="-1"
        eType="#//ConfigurationOption" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VersionNumber">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="versionNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Query" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="RegularQuery" eSuperTypes="#//Query">
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleQuery" eType="#//RegularQuery"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="union" upperBound="-1"
        eType="#//Union" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BulkImportQuery" eSuperTypes="#//Query">
    <eStructuralFeatures xsi:type="ecore:EReference" name="periodicCommitHint" eType="#//PeriodicCommitHint"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loadCSVQuery" eType="#//LoadCSVQuery"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleQuery" eSuperTypes="#//RegularQuery">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clauses" upperBound="-1"
        eType="#//Clause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PeriodicCommitHint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="numberOfRowsPerCommit"
        eType="#//DecimalInteger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadCSVQuery">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loadCSV" eType="#//LoadCSV"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clauses" upperBound="-1"
        eType="#//Clause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Union">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="all" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleQuery" eType="#//SingleQuery"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Clause"/>
  <eClassifiers xsi:type="ecore:EClass" name="Command" eSuperTypes="#//Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateUniqueConstraint" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateNodePropertyExistenceConstraint"
      eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateRelationshipPropertyExistenceConstraint"
      eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="CreateIndex" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//Index"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DropUniqueConstraint" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="uniqueConstraint" eType="#//UniqueConstraint"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DropNodePropertyExistenceConstraint"
      eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodePropertyExistenceConstraint"
        eType="#//NodePropertyExistenceConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DropRelationshipPropertyExistenceConstraint"
      eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationshipPropertyExistenceConstraint"
        eType="#//RelationshipPropertyExistenceConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DropIndex" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//Index"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index" eSuperTypes="#//Expression3Part">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeLabel" eType="#//NodeLabel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyKeyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upper" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueConstraint" eSuperTypes="#//CreateUniqueConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeLabel" eType="#//NodeLabel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyExpression" eType="#//PropertyExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodePropertyExistenceConstraint" eSuperTypes="#//CreateNodePropertyExistenceConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeLabel" eType="#//NodeLabel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyExpression" eType="#//PropertyExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipPropertyExistenceConstraint"
      eSuperTypes="#//CreateRelationshipPropertyExistenceConstraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationshipPattern" eType="#//RelationshipPatternSyntax"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyExpression" eType="#//PropertyExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipPatternSyntax">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incoming" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outgoing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadCSV" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="withHeaders" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fieldterminator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Match" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//Pattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hints" upperBound="-1"
        eType="#//Hint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//Where"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unwind" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Merge" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternPart" eType="#//PatternPart"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mergeActions" upperBound="-1"
        eType="#//MergeAction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MergeAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="set" eType="#//Set" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Create" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="#//Pattern"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Set" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="setItems" upperBound="-1"
        eType="#//SetItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyExpression" eType="#//PropertyExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeLabels" eType="#//NodeLabels"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delete" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="detach" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Remove" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="removeItems" upperBound="-1"
        eType="#//RemoveItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RemoveItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeLabels" eType="#//NodeLabels"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foreach" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clause" upperBound="-1"
        eType="#//Clause" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="With" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnBody" eType="#//ReturnBody"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//Where"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Return" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="return" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distinct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="#//ReturnBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnBody"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnItems" eSuperTypes="#//ReturnBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="order" eType="#//Order"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="skip" eType="#//Skip" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="limit" eType="#//Limit"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="all" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//ReturnItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alias" eType="#//Variable"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Order">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orderBy" upperBound="-1"
        eType="#//SortItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Skip">
    <eStructuralFeatures xsi:type="ecore:EReference" name="skip" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Limit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="limit" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SortItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Hint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Start" eSuperTypes="#//Clause">
    <eStructuralFeatures xsi:type="ecore:EReference" name="startPoint" upperBound="-1"
        eType="#//StartPoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//Where"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartPoint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lookup" eType="#//Lookup"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lookup"/>
  <eClassifiers xsi:type="ecore:EClass" name="NodeLookup" eSuperTypes="#//Lookup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipLookup" eSuperTypes="#//Lookup"/>
  <eClassifiers xsi:type="ecore:EClass" name="IdentifiedIndexLookup" eSuperTypes="#//NodeLookup #//RelationshipLookup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyParameter" eType="#//LegacyParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexQuery" eSuperTypes="#//NodeLookup #//RelationshipLookup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="indexName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="query" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" eType="#//Parameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdLookup" eSuperTypes="#//NodeLookup #//RelationshipLookup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ids" eType="#//LiteralIds"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="legacyParameter" eType="#//Parameter"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wildcard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LiteralIds">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ids" upperBound="-1" eType="#//DecimalInteger"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Where">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patterns" upperBound="-1"
        eType="#//PatternPart" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="part" eType="#//AnonymousPatternPart"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnonymousPatternPart" eSuperTypes="#//PatternPart"/>
  <eClassifiers xsi:type="ecore:EClass" name="ShortestPathPattern" eSuperTypes="#//AnonymousPatternPart #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternElement" eType="#//PatternElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternElement" eSuperTypes="#//AnonymousPatternPart">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodepattern" eType="#//NodePattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chain" upperBound="-1"
        eType="#//PatternElementChain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodePattern">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeLabels" eType="#//NodeLabels"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" eType="#//Properties"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternElementChain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relationshipPattern" eType="#//RelationshipPattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodePattern" eType="#//NodePattern"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipPattern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="incoming" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="detail" eType="#//RelationshipDetail"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outgoing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipDetail">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" eType="#//RelationshipTypes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="range" eType="#//RangeLiteral"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" eType="#//Properties"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Properties"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipTypes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relTypeName" unique="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeLabels">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeLabels" upperBound="-1"
        eType="#//NodeLabel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeLabel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labelName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RangeLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//PropertyExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression3Parts" upperBound="-1"
        eType="#//Expression3Part" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeLabelList" upperBound="-1"
        eType="#//NodeLabel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyLoopup" upperBound="-1"
        eType="#//PropertyLookup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression3Part"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reduce" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accumulator" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accumulatorExpression"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="idInColl" eType="#//IdInColl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParenthesizedExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RelationshipsPattern" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodePattern" eType="#//NodePattern"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chain" upperBound="-1"
        eType="#//PatternElementChain" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilterExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="idInColl" eType="#//IdInColl"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="where" eType="#//Where"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdInColl">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionInvocation" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="functionName" eType="#//FunctionName"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distinct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListComprehension" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterExpression" eType="#//FilterExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyLookup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyKeyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyOperator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CaseExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//CaseExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="caseAlternatives" upperBound="-1"
        eType="#//CaseAlternatives" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="caseExpression" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elseExpression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CaseAlternatives">
    <eStructuralFeatures xsi:type="ecore:EReference" name="when" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="then" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapLiteral" eSuperTypes="#//Properties #//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//MapLiteralEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapLiteralEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyParameter" eSuperTypes="#//Properties #//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="#//Properties #//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyExpression" eSuperTypes="#//RemoveItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="DecimalInteger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AllOptions" eSuperTypes="#//QueryOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cypherOption" upperBound="-1"
        eType="#//CypherOption" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndexHint" eSuperTypes="#//Hint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeLabel" eType="#//NodeLabel"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyKeyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinHint" eSuperTypes="#//Hint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScanHint" eSuperTypes="#//Hint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" eType="#//Variable"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeLabel" eType="#//NodeLabel"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShortestPath" eSuperTypes="#//ShortestPathPattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="AllShortestPath" eSuperTypes="#//ShortestPathPattern"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionOr" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionXor" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionAnd" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionComparison" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionPlusMinus" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionMulDiv" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionPower" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RegExpMatching" eSuperTypes="#//Expression3Part">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InCollection" eSuperTypes="#//Expression3Part">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StartsWith" eSuperTypes="#//Expression3Part">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndsWith" eSuperTypes="#//Expression3Part">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contains" eSuperTypes="#//Expression3Part">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsNull" eSuperTypes="#//Expression3Part"/>
  <eClassifiers xsi:type="ecore:EClass" name="IsNotNull" eSuperTypes="#//Expression3Part"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionNodeLabelsAndPropertyLookup"
      eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyLookups" upperBound="-1"
        eType="#//PropertyLookup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumberConstant" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringConstant" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolConstant" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NullConstant" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Count" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpressionList" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Filter" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterExpression" eType="#//FilterExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="All" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterExpression" eType="#//FilterExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Any" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterExpression" eType="#//FilterExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="None" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterExpression" eType="#//FilterExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Single" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterExpression" eType="#//FilterExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRef" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variableRef" eType="#//Variable"/>
  </eClassifiers>
</ecore:EPackage>
