/**
 * generated by Xtext 2.10.0
 */
package ingraph.report.feature;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Scenario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link ingraph.report.feature.AbstractScenario#getTags <em>Tags</em>}</li>
 *   <li>{@link ingraph.report.feature.AbstractScenario#getName <em>Name</em>}</li>
 *   <li>{@link ingraph.report.feature.AbstractScenario#getSteps <em>Steps</em>}</li>
 * </ul>
 *
 * @see ingraph.report.feature.FeaturePackage#getAbstractScenario()
 * @model
 * @generated
 */
public interface AbstractScenario extends EObject
{
  /**
   * Returns the value of the '<em><b>Tags</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tags</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tags</em>' attribute list.
   * @see ingraph.report.feature.FeaturePackage#getAbstractScenario_Tags()
   * @model unique="false"
   * @generated
   */
  EList<String> getTags();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see ingraph.report.feature.FeaturePackage#getAbstractScenario_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link ingraph.report.feature.AbstractScenario#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Steps</b></em>' containment reference list.
   * The list contents are of type {@link ingraph.report.feature.Step}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Steps</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Steps</em>' containment reference list.
   * @see ingraph.report.feature.FeaturePackage#getAbstractScenario_Steps()
   * @model containment="true"
   * @generated
   */
  EList<Step> getSteps();

} // AbstractScenario
