/**
 * generated by Xtext 2.10.0
 */
package ingraph.report.feature;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>As A</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see ingraph.report.feature.FeaturePackage#getAsA()
 * @model
 * @generated
 */
public interface AsA extends NarrativeElement
{
} // AsA
