<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="relalg" nsURI="http://www.example.org/relalg" nsPrefix="relalg">
  <eClassifiers xsi:type="ecore:EClass" name="Operator" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" upperBound="-1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectionOperator" eSuperTypes="#//AlphaOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinOperator" eSuperTypes="#//AbstractJoinOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlphaOperator" abstract="true" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" eType="#//Operator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BetaOperator" abstract="true" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftInput" lowerBound="1"
        eType="#//Operator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightInput" lowerBound="1"
        eType="#//Operator" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AntiJoinOperator" eSuperTypes="#//AbstractJoinOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProductionOperator" eSuperTypes="#//AlphaOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelectionOperator" eSuperTypes="#//AlphaOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conditionString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExpandOperator" eSuperTypes="#//AlphaOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//Direction"
        defaultValueLiteral="IN"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeVariable" lowerBound="1"
        eType="#//EdgeVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceVertexVariable" lowerBound="1"
        eType="#//VertexVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetVertexVariable" lowerBound="1"
        eType="#//VertexVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="BOTH"/>
    <eLiterals name="IN" value="1"/>
    <eLiterals name="OUT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetVerticesOperator" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="DuplicateEliminationOperator" eSuperTypes="#//AlphaOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true" eSuperTypes="#//NamedElement #//ReturnableElement #//Comparable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dontCare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VertexVariable" eSuperTypes="#//ElementVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeVariable" eSuperTypes="#//ElementVariable"/>
  <eClassifiers xsi:type="ecore:EClass" name="Label" abstract="true" eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="VertexLabel" eSuperTypes="#//Label"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeLabel" eSuperTypes="#//Label"/>
  <eClassifiers xsi:type="ecore:EClass" name="AllDifferentOperator" eSuperTypes="#//AlphaOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeVariables" upperBound="-1"
        eType="#//EdgeVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeVariable" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" lowerBound="1"
        eType="#//ElementVariable" eOpposite="#//ElementVariable/attributes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" lowerBound="1"
        eType="#//Container" eOpposite="#//Container/elements"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnionOperator" eSuperTypes="#//BetaOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootExpression" eType="#//Operator"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//NamedElement" containment="true" eOpposite="#//NamedElement/container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArithmeticComparisonOperator">
    <eLiterals name="EQUAL_TO" literal="="/>
    <eLiterals name="NOT_EQUAL_TO" value="1" literal="!="/>
    <eLiterals name="GREATER_THAN" value="2" literal=">"/>
    <eLiterals name="GREATER_THAN_OR_EQUAL" value="3" literal=">="/>
    <eLiterals name="LESS_THAN" value="4" literal="&lt;"/>
    <eLiterals name="LESS_THAN_OR_EQUAL" value="5" literal="&lt;="/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//ReturnableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReturnableElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EEnum" name="StringComparisonOperator">
    <eLiterals name="MATCHES" literal="=~"/>
    <eLiterals name="IN" value="1"/>
    <eLiterals name="STARTS_WITH" value="2" literal="STARTS WITH"/>
    <eLiterals name="ENDS_WITH" value="3" literal="ENDS WITH"/>
    <eLiterals name="CONTAINS" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticOperationExpression" eSuperTypes="#//BinaryExpression #//Comparable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//BinaryArithmeticOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryLogicalExpression" eSuperTypes="#//BinaryExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//BinaryLogicalOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArithmeticComparisonExpression" eSuperTypes="#//ComparisonExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//ArithmeticComparisonOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="negated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringComparisonExpression" eSuperTypes="#//ComparisonExpression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//StringComparisonOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryLogicalOperator">
    <eLiterals name="OR"/>
    <eLiterals name="XOR" value="1"/>
    <eLiterals name="AND" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BinaryArithmeticOperator">
    <eLiterals name="PLUS" literal="+"/>
    <eLiterals name="MINUS" value="1" literal="-"/>
    <eLiterals name="MULTIPLICATION" value="2" literal="*"/>
    <eLiterals name="DIVISION" value="3" literal="/"/>
    <eLiterals name="MOD" value="4" literal="%"/>
    <eLiterals name="POWER" value="5" literal="^"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnaryArithmeticOperator">
    <eLiterals name="PLUS" literal="+"/>
    <eLiterals name="MINUS" value="1" literal="-"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Order">
    <eLiterals name="DESCENDING" literal="DESCENDING"/>
    <eLiterals name="ASCENDING" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Literal" abstract="true" eSuperTypes="#//Atom #//Comparable"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumberLiteral" abstract="true" eSuperTypes="#//Literal"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Literal">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleLiteral" eSuperTypes="#//NumberLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteral" eSuperTypes="#//NumberLiteral">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetEdgesOperator" eSuperTypes="#//Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Comparable" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ElementVariable" abstract="true" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//AttributeVariable" eOpposite="#//AttributeVariable/element"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComparisonExpression" abstract="true"
      eSuperTypes="#//BinaryExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftOperand" lowerBound="1"
        eType="#//Comparable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightOperand" lowerBound="1"
        eType="#//Comparable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractJoinOperator" abstract="true"
      eSuperTypes="#//BetaOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mutualVariables" upperBound="-1"
        eType="#//Variable"/>
  </eClassifiers>
</ecore:EPackage>
