<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="relalg" nsURI="http://www.example.org/relalg" nsPrefix="relalg">
  <eClassifiers xsi:type="ecore:EClass" name="AlgebraExpression" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectionOperator" eSuperTypes="#//AlphaOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JoinOperator" eSuperTypes="#//BetaOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlphaOperator" abstract="true" eSuperTypes="#//AlgebraExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" lowerBound="1"
        eType="#//AlgebraExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BetaOperator" abstract="true" eSuperTypes="#//AlgebraExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftParent" lowerBound="1"
        eType="#//AlgebraExpression"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightParent" lowerBound="1"
        eType="#//AlgebraExpression"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AntiJoinOperator" eSuperTypes="#//BetaOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProductionOperator" eSuperTypes="#//AlphaOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="FilterOperator" eSuperTypes="#//AlphaOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpandOperator" eSuperTypes="#//AlphaOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//Direction"
        defaultValueLiteral="IN"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeVariable" lowerBound="1"
        eType="#//EdgeVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceVertexVariable" lowerBound="1"
        eType="#//VertexVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetVertexVariable" lowerBound="1"
        eType="#//VertexVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Direction">
    <eLiterals name="BOTH"/>
    <eLiterals name="IN" value="1"/>
    <eLiterals name="OUT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GetVerticesOperator" eSuperTypes="#//AlgebraExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertexVariable" lowerBound="1"
        eType="#//VertexVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertexLabel" lowerBound="1"
        eType="#//VertexLabel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DuplicateEliminationOperator" eSuperTypes="#//AlphaOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dontCare" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VertexVariable" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertexLabel" lowerBound="1"
        eType="#//VertexLabel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeVariable" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeLabel" lowerBound="1"
        eType="#//EdgeLabel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Label" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VertexLabel" eSuperTypes="#//Label"/>
  <eClassifiers xsi:type="ecore:EClass" name="EdgeLabel" eSuperTypes="#//Label"/>
  <eClassifiers xsi:type="ecore:EClass" name="AllDifferentOperator" eSuperTypes="#//AlphaOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edgeVariables" upperBound="-1"
        eType="#//EdgeVariable"/>
  </eClassifiers>
</ecore:EPackage>
