/**
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.opencypher.openCypher.impl;

import org.eclipse.emf.ecore.EClass;

import org.slizaa.neo4j.opencypher.openCypher.AnonymousPatternPart;
import org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Anonymous Pattern Part</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AnonymousPatternPartImpl extends PatternPartImpl implements AnonymousPatternPart
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AnonymousPatternPartImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenCypherPackage.Literals.ANONYMOUS_PATTERN_PART;
  }

} //AnonymousPatternPartImpl
