/**
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.opencypher.openCypher.impl;

import org.eclipse.emf.ecore.EClass;

import org.slizaa.neo4j.opencypher.openCypher.CreateRelationshipPropertyExistenceConstraint;
import org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Create Relationship Property Existence Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CreateRelationshipPropertyExistenceConstraintImpl extends CommandImpl implements CreateRelationshipPropertyExistenceConstraint
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CreateRelationshipPropertyExistenceConstraintImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenCypherPackage.Literals.CREATE_RELATIONSHIP_PROPERTY_EXISTENCE_CONSTRAINT;
  }

} //CreateRelationshipPropertyExistenceConstraintImpl
