/**
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.opencypher.openCypher.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.slizaa.neo4j.opencypher.openCypher.FilterExpression;
import org.slizaa.neo4j.opencypher.openCypher.IdInColl;
import org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage;
import org.slizaa.neo4j.opencypher.openCypher.Where;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Filter Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.impl.FilterExpressionImpl#getIdInColl <em>Id In Coll</em>}</li>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.impl.FilterExpressionImpl#getWhere <em>Where</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FilterExpressionImpl extends MinimalEObjectImpl.Container implements FilterExpression
{
  /**
   * The cached value of the '{@link #getIdInColl() <em>Id In Coll</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdInColl()
   * @generated
   * @ordered
   */
  protected IdInColl idInColl;

  /**
   * The cached value of the '{@link #getWhere() <em>Where</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWhere()
   * @generated
   * @ordered
   */
  protected Where where;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FilterExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenCypherPackage.Literals.FILTER_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IdInColl getIdInColl()
  {
    return idInColl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIdInColl(IdInColl newIdInColl, NotificationChain msgs)
  {
    IdInColl oldIdInColl = idInColl;
    idInColl = newIdInColl;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenCypherPackage.FILTER_EXPRESSION__ID_IN_COLL, oldIdInColl, newIdInColl);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIdInColl(IdInColl newIdInColl)
  {
    if (newIdInColl != idInColl)
    {
      NotificationChain msgs = null;
      if (idInColl != null)
        msgs = ((InternalEObject)idInColl).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.FILTER_EXPRESSION__ID_IN_COLL, null, msgs);
      if (newIdInColl != null)
        msgs = ((InternalEObject)newIdInColl).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.FILTER_EXPRESSION__ID_IN_COLL, null, msgs);
      msgs = basicSetIdInColl(newIdInColl, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenCypherPackage.FILTER_EXPRESSION__ID_IN_COLL, newIdInColl, newIdInColl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Where getWhere()
  {
    return where;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWhere(Where newWhere, NotificationChain msgs)
  {
    Where oldWhere = where;
    where = newWhere;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenCypherPackage.FILTER_EXPRESSION__WHERE, oldWhere, newWhere);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setWhere(Where newWhere)
  {
    if (newWhere != where)
    {
      NotificationChain msgs = null;
      if (where != null)
        msgs = ((InternalEObject)where).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.FILTER_EXPRESSION__WHERE, null, msgs);
      if (newWhere != null)
        msgs = ((InternalEObject)newWhere).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.FILTER_EXPRESSION__WHERE, null, msgs);
      msgs = basicSetWhere(newWhere, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenCypherPackage.FILTER_EXPRESSION__WHERE, newWhere, newWhere));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OpenCypherPackage.FILTER_EXPRESSION__ID_IN_COLL:
        return basicSetIdInColl(null, msgs);
      case OpenCypherPackage.FILTER_EXPRESSION__WHERE:
        return basicSetWhere(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OpenCypherPackage.FILTER_EXPRESSION__ID_IN_COLL:
        return getIdInColl();
      case OpenCypherPackage.FILTER_EXPRESSION__WHERE:
        return getWhere();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OpenCypherPackage.FILTER_EXPRESSION__ID_IN_COLL:
        setIdInColl((IdInColl)newValue);
        return;
      case OpenCypherPackage.FILTER_EXPRESSION__WHERE:
        setWhere((Where)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OpenCypherPackage.FILTER_EXPRESSION__ID_IN_COLL:
        setIdInColl((IdInColl)null);
        return;
      case OpenCypherPackage.FILTER_EXPRESSION__WHERE:
        setWhere((Where)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OpenCypherPackage.FILTER_EXPRESSION__ID_IN_COLL:
        return idInColl != null;
      case OpenCypherPackage.FILTER_EXPRESSION__WHERE:
        return where != null;
    }
    return super.eIsSet(featureID);
  }

} //FilterExpressionImpl
