/**
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.opencypher.openCypher.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.slizaa.neo4j.opencypher.openCypher.Expression;
import org.slizaa.neo4j.opencypher.openCypher.Expression3Part;
import org.slizaa.neo4j.opencypher.openCypher.NodeLabel;
import org.slizaa.neo4j.opencypher.openCypher.NodeLabels;
import org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage;
import org.slizaa.neo4j.opencypher.openCypher.Parameter;
import org.slizaa.neo4j.opencypher.openCypher.PropertyExpression;
import org.slizaa.neo4j.opencypher.openCypher.PropertyLookup;
import org.slizaa.neo4j.opencypher.openCypher.RemoveItem;
import org.slizaa.neo4j.opencypher.openCypher.Variable;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.impl.ParameterImpl#getVariable <em>Variable</em>}</li>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.impl.ParameterImpl#getNodeLabels <em>Node Labels</em>}</li>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.impl.ParameterImpl#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.impl.ParameterImpl#getLeft <em>Left</em>}</li>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.impl.ParameterImpl#getExpression3Parts <em>Expression3 Parts</em>}</li>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.impl.ParameterImpl#getNodeLabelList <em>Node Label List</em>}</li>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.impl.ParameterImpl#getPropertyLookup <em>Property Lookup</em>}</li>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.impl.ParameterImpl#getParameter <em>Parameter</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ParameterImpl extends PropertiesImpl implements Parameter
{
  /**
   * The cached value of the '{@link #getVariable() <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariable()
   * @generated
   * @ordered
   */
  protected Variable variable;

  /**
   * The cached value of the '{@link #getNodeLabels() <em>Node Labels</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNodeLabels()
   * @generated
   * @ordered
   */
  protected NodeLabels nodeLabels;

  /**
   * The default value of the '{@link #getOperator() <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected static final String OPERATOR_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOperator() <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOperator()
   * @generated
   * @ordered
   */
  protected String operator = OPERATOR_EDEFAULT;

  /**
   * The cached value of the '{@link #getLeft() <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLeft()
   * @generated
   * @ordered
   */
  protected Expression left;

  /**
   * The cached value of the '{@link #getExpression3Parts() <em>Expression3 Parts</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExpression3Parts()
   * @generated
   * @ordered
   */
  protected EList<Expression3Part> expression3Parts;

  /**
   * The cached value of the '{@link #getNodeLabelList() <em>Node Label List</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNodeLabelList()
   * @generated
   * @ordered
   */
  protected EList<NodeLabel> nodeLabelList;

  /**
   * The cached value of the '{@link #getPropertyLookup() <em>Property Lookup</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPropertyLookup()
   * @generated
   * @ordered
   */
  protected EList<PropertyLookup> propertyLookup;

  /**
   * The default value of the '{@link #getParameter() <em>Parameter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameter()
   * @generated
   * @ordered
   */
  protected static final String PARAMETER_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getParameter() <em>Parameter</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameter()
   * @generated
   * @ordered
   */
  protected String parameter = PARAMETER_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ParameterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenCypherPackage.Literals.PARAMETER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Variable getVariable()
  {
    return variable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVariable(Variable newVariable, NotificationChain msgs)
  {
    Variable oldVariable = variable;
    variable = newVariable;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenCypherPackage.PARAMETER__VARIABLE, oldVariable, newVariable);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setVariable(Variable newVariable)
  {
    if (newVariable != variable)
    {
      NotificationChain msgs = null;
      if (variable != null)
        msgs = ((InternalEObject)variable).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.PARAMETER__VARIABLE, null, msgs);
      if (newVariable != null)
        msgs = ((InternalEObject)newVariable).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.PARAMETER__VARIABLE, null, msgs);
      msgs = basicSetVariable(newVariable, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenCypherPackage.PARAMETER__VARIABLE, newVariable, newVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NodeLabels getNodeLabels()
  {
    return nodeLabels;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNodeLabels(NodeLabels newNodeLabels, NotificationChain msgs)
  {
    NodeLabels oldNodeLabels = nodeLabels;
    nodeLabels = newNodeLabels;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenCypherPackage.PARAMETER__NODE_LABELS, oldNodeLabels, newNodeLabels);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNodeLabels(NodeLabels newNodeLabels)
  {
    if (newNodeLabels != nodeLabels)
    {
      NotificationChain msgs = null;
      if (nodeLabels != null)
        msgs = ((InternalEObject)nodeLabels).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.PARAMETER__NODE_LABELS, null, msgs);
      if (newNodeLabels != null)
        msgs = ((InternalEObject)newNodeLabels).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.PARAMETER__NODE_LABELS, null, msgs);
      msgs = basicSetNodeLabels(newNodeLabels, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenCypherPackage.PARAMETER__NODE_LABELS, newNodeLabels, newNodeLabels));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getOperator()
  {
    return operator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setOperator(String newOperator)
  {
    String oldOperator = operator;
    operator = newOperator;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenCypherPackage.PARAMETER__OPERATOR, oldOperator, operator));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Expression getLeft()
  {
    return left;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetLeft(Expression newLeft, NotificationChain msgs)
  {
    Expression oldLeft = left;
    left = newLeft;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OpenCypherPackage.PARAMETER__LEFT, oldLeft, newLeft);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setLeft(Expression newLeft)
  {
    if (newLeft != left)
    {
      NotificationChain msgs = null;
      if (left != null)
        msgs = ((InternalEObject)left).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.PARAMETER__LEFT, null, msgs);
      if (newLeft != null)
        msgs = ((InternalEObject)newLeft).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OpenCypherPackage.PARAMETER__LEFT, null, msgs);
      msgs = basicSetLeft(newLeft, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenCypherPackage.PARAMETER__LEFT, newLeft, newLeft));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Expression3Part> getExpression3Parts()
  {
    if (expression3Parts == null)
    {
      expression3Parts = new EObjectContainmentEList<Expression3Part>(Expression3Part.class, this, OpenCypherPackage.PARAMETER__EXPRESSION3_PARTS);
    }
    return expression3Parts;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<NodeLabel> getNodeLabelList()
  {
    if (nodeLabelList == null)
    {
      nodeLabelList = new EObjectContainmentEList<NodeLabel>(NodeLabel.class, this, OpenCypherPackage.PARAMETER__NODE_LABEL_LIST);
    }
    return nodeLabelList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<PropertyLookup> getPropertyLookup()
  {
    if (propertyLookup == null)
    {
      propertyLookup = new EObjectContainmentEList<PropertyLookup>(PropertyLookup.class, this, OpenCypherPackage.PARAMETER__PROPERTY_LOOKUP);
    }
    return propertyLookup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getParameter()
  {
    return parameter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParameter(String newParameter)
  {
    String oldParameter = parameter;
    parameter = newParameter;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OpenCypherPackage.PARAMETER__PARAMETER, oldParameter, parameter));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OpenCypherPackage.PARAMETER__VARIABLE:
        return basicSetVariable(null, msgs);
      case OpenCypherPackage.PARAMETER__NODE_LABELS:
        return basicSetNodeLabels(null, msgs);
      case OpenCypherPackage.PARAMETER__LEFT:
        return basicSetLeft(null, msgs);
      case OpenCypherPackage.PARAMETER__EXPRESSION3_PARTS:
        return ((InternalEList<?>)getExpression3Parts()).basicRemove(otherEnd, msgs);
      case OpenCypherPackage.PARAMETER__NODE_LABEL_LIST:
        return ((InternalEList<?>)getNodeLabelList()).basicRemove(otherEnd, msgs);
      case OpenCypherPackage.PARAMETER__PROPERTY_LOOKUP:
        return ((InternalEList<?>)getPropertyLookup()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OpenCypherPackage.PARAMETER__VARIABLE:
        return getVariable();
      case OpenCypherPackage.PARAMETER__NODE_LABELS:
        return getNodeLabels();
      case OpenCypherPackage.PARAMETER__OPERATOR:
        return getOperator();
      case OpenCypherPackage.PARAMETER__LEFT:
        return getLeft();
      case OpenCypherPackage.PARAMETER__EXPRESSION3_PARTS:
        return getExpression3Parts();
      case OpenCypherPackage.PARAMETER__NODE_LABEL_LIST:
        return getNodeLabelList();
      case OpenCypherPackage.PARAMETER__PROPERTY_LOOKUP:
        return getPropertyLookup();
      case OpenCypherPackage.PARAMETER__PARAMETER:
        return getParameter();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OpenCypherPackage.PARAMETER__VARIABLE:
        setVariable((Variable)newValue);
        return;
      case OpenCypherPackage.PARAMETER__NODE_LABELS:
        setNodeLabels((NodeLabels)newValue);
        return;
      case OpenCypherPackage.PARAMETER__OPERATOR:
        setOperator((String)newValue);
        return;
      case OpenCypherPackage.PARAMETER__LEFT:
        setLeft((Expression)newValue);
        return;
      case OpenCypherPackage.PARAMETER__EXPRESSION3_PARTS:
        getExpression3Parts().clear();
        getExpression3Parts().addAll((Collection<? extends Expression3Part>)newValue);
        return;
      case OpenCypherPackage.PARAMETER__NODE_LABEL_LIST:
        getNodeLabelList().clear();
        getNodeLabelList().addAll((Collection<? extends NodeLabel>)newValue);
        return;
      case OpenCypherPackage.PARAMETER__PROPERTY_LOOKUP:
        getPropertyLookup().clear();
        getPropertyLookup().addAll((Collection<? extends PropertyLookup>)newValue);
        return;
      case OpenCypherPackage.PARAMETER__PARAMETER:
        setParameter((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OpenCypherPackage.PARAMETER__VARIABLE:
        setVariable((Variable)null);
        return;
      case OpenCypherPackage.PARAMETER__NODE_LABELS:
        setNodeLabels((NodeLabels)null);
        return;
      case OpenCypherPackage.PARAMETER__OPERATOR:
        setOperator(OPERATOR_EDEFAULT);
        return;
      case OpenCypherPackage.PARAMETER__LEFT:
        setLeft((Expression)null);
        return;
      case OpenCypherPackage.PARAMETER__EXPRESSION3_PARTS:
        getExpression3Parts().clear();
        return;
      case OpenCypherPackage.PARAMETER__NODE_LABEL_LIST:
        getNodeLabelList().clear();
        return;
      case OpenCypherPackage.PARAMETER__PROPERTY_LOOKUP:
        getPropertyLookup().clear();
        return;
      case OpenCypherPackage.PARAMETER__PARAMETER:
        setParameter(PARAMETER_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OpenCypherPackage.PARAMETER__VARIABLE:
        return variable != null;
      case OpenCypherPackage.PARAMETER__NODE_LABELS:
        return nodeLabels != null;
      case OpenCypherPackage.PARAMETER__OPERATOR:
        return OPERATOR_EDEFAULT == null ? operator != null : !OPERATOR_EDEFAULT.equals(operator);
      case OpenCypherPackage.PARAMETER__LEFT:
        return left != null;
      case OpenCypherPackage.PARAMETER__EXPRESSION3_PARTS:
        return expression3Parts != null && !expression3Parts.isEmpty();
      case OpenCypherPackage.PARAMETER__NODE_LABEL_LIST:
        return nodeLabelList != null && !nodeLabelList.isEmpty();
      case OpenCypherPackage.PARAMETER__PROPERTY_LOOKUP:
        return propertyLookup != null && !propertyLookup.isEmpty();
      case OpenCypherPackage.PARAMETER__PARAMETER:
        return PARAMETER_EDEFAULT == null ? parameter != null : !PARAMETER_EDEFAULT.equals(parameter);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == RemoveItem.class)
    {
      switch (derivedFeatureID)
      {
        case OpenCypherPackage.PARAMETER__VARIABLE: return OpenCypherPackage.REMOVE_ITEM__VARIABLE;
        case OpenCypherPackage.PARAMETER__NODE_LABELS: return OpenCypherPackage.REMOVE_ITEM__NODE_LABELS;
        default: return -1;
      }
    }
    if (baseClass == PropertyExpression.class)
    {
      switch (derivedFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == Expression.class)
    {
      switch (derivedFeatureID)
      {
        case OpenCypherPackage.PARAMETER__OPERATOR: return OpenCypherPackage.EXPRESSION__OPERATOR;
        case OpenCypherPackage.PARAMETER__LEFT: return OpenCypherPackage.EXPRESSION__LEFT;
        case OpenCypherPackage.PARAMETER__EXPRESSION3_PARTS: return OpenCypherPackage.EXPRESSION__EXPRESSION3_PARTS;
        case OpenCypherPackage.PARAMETER__NODE_LABEL_LIST: return OpenCypherPackage.EXPRESSION__NODE_LABEL_LIST;
        case OpenCypherPackage.PARAMETER__PROPERTY_LOOKUP: return OpenCypherPackage.EXPRESSION__PROPERTY_LOOKUP;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == RemoveItem.class)
    {
      switch (baseFeatureID)
      {
        case OpenCypherPackage.REMOVE_ITEM__VARIABLE: return OpenCypherPackage.PARAMETER__VARIABLE;
        case OpenCypherPackage.REMOVE_ITEM__NODE_LABELS: return OpenCypherPackage.PARAMETER__NODE_LABELS;
        default: return -1;
      }
    }
    if (baseClass == PropertyExpression.class)
    {
      switch (baseFeatureID)
      {
        default: return -1;
      }
    }
    if (baseClass == Expression.class)
    {
      switch (baseFeatureID)
      {
        case OpenCypherPackage.EXPRESSION__OPERATOR: return OpenCypherPackage.PARAMETER__OPERATOR;
        case OpenCypherPackage.EXPRESSION__LEFT: return OpenCypherPackage.PARAMETER__LEFT;
        case OpenCypherPackage.EXPRESSION__EXPRESSION3_PARTS: return OpenCypherPackage.PARAMETER__EXPRESSION3_PARTS;
        case OpenCypherPackage.EXPRESSION__NODE_LABEL_LIST: return OpenCypherPackage.PARAMETER__NODE_LABEL_LIST;
        case OpenCypherPackage.EXPRESSION__PROPERTY_LOOKUP: return OpenCypherPackage.PARAMETER__PROPERTY_LOOKUP;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (operator: ");
    result.append(operator);
    result.append(", parameter: ");
    result.append(parameter);
    result.append(')');
    return result.toString();
  }

} //ParameterImpl
