/**
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.opencypher.openCypher.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage;
import org.slizaa.neo4j.opencypher.openCypher.ReturnBody;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Return Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ReturnBodyImpl extends MinimalEObjectImpl.Container implements ReturnBody
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReturnBodyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OpenCypherPackage.Literals.RETURN_BODY;
  }

} //ReturnBodyImpl
