/**
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.opencypher.openCypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Anonymous Pattern Part</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage#getAnonymousPatternPart()
 * @model
 * @generated
 */
public interface AnonymousPatternPart extends PatternPart
{
} // AnonymousPatternPart
