/**
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.opencypher.openCypher;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Node Labels And Property Lookup</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.slizaa.neo4j.opencypher.openCypher.ExpressionNodeLabelsAndPropertyLookup#getPropertyLookups <em>Property Lookups</em>}</li>
 * </ul>
 *
 * @see org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage#getExpressionNodeLabelsAndPropertyLookup()
 * @model
 * @generated
 */
public interface ExpressionNodeLabelsAndPropertyLookup extends Expression
{
  /**
   * Returns the value of the '<em><b>Property Lookups</b></em>' containment reference list.
   * The list contents are of type {@link org.slizaa.neo4j.opencypher.openCypher.PropertyLookup}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Property Lookups</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property Lookups</em>' containment reference list.
   * @see org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage#getExpressionNodeLabelsAndPropertyLookup_PropertyLookups()
   * @model containment="true"
   * @generated
   */
  EList<PropertyLookup> getPropertyLookups();

} // ExpressionNodeLabelsAndPropertyLookup
