/**
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.opencypher.openCypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Node Lookup</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage#getNodeLookup()
 * @model
 * @generated
 */
public interface NodeLookup extends Lookup
{
} // NodeLookup
