/**
 * generated by Xtext 2.10.0
 */
package org.slizaa.neo4j.opencypher.openCypher;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Relationship Lookup</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.slizaa.neo4j.opencypher.openCypher.OpenCypherPackage#getRelationshipLookup()
 * @model
 * @generated
 */
public interface RelationshipLookup extends Lookup
{
} // RelationshipLookup
