/**
 * generated by Xtext 2.10.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern Element Chain</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PatternElementChain#getRelationshipPattern <em>Relationship Pattern</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.PatternElementChain#getNodePattern <em>Node Pattern</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPatternElementChain()
 * @model
 * @generated
 */
public interface PatternElementChain extends EObject
{
  /**
   * Returns the value of the '<em><b>Relationship Pattern</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Relationship Pattern</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationship Pattern</em>' containment reference.
   * @see #setRelationshipPattern(RelationshipPattern)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPatternElementChain_RelationshipPattern()
   * @model containment="true"
   * @generated
   */
  RelationshipPattern getRelationshipPattern();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PatternElementChain#getRelationshipPattern <em>Relationship Pattern</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relationship Pattern</em>' containment reference.
   * @see #getRelationshipPattern()
   * @generated
   */
  void setRelationshipPattern(RelationshipPattern value);

  /**
   * Returns the value of the '<em><b>Node Pattern</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node Pattern</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node Pattern</em>' containment reference.
   * @see #setNodePattern(NodePattern)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getPatternElementChain_NodePattern()
   * @model containment="true"
   * @generated
   */
  NodePattern getNodePattern();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.PatternElementChain#getNodePattern <em>Node Pattern</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node Pattern</em>' containment reference.
   * @see #getNodePattern()
   * @generated
   */
  void setNodePattern(NodePattern value);

} // PatternElementChain
