/**
 * generated by Xtext 2.10.0
 */
package ingraph.report.feature.impl;

import org.eclipse.emf.ecore.EClass;

import ingraph.report.feature.AndStep;
import ingraph.report.feature.FeaturePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>And Step</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AndStepImpl extends StepImpl implements AndStep
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AndStepImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FeaturePackage.Literals.AND_STEP;
  }

} //AndStepImpl
