/**
 * generated by Xtext 2.10.0
 */
package ingraph.report.feature.impl;

import org.eclipse.emf.ecore.EClass;

import ingraph.report.feature.FeaturePackage;
import ingraph.report.feature.FreeText;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Free Text</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FreeTextImpl extends NarrativeElementImpl implements FreeText
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FreeTextImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FeaturePackage.Literals.FREE_TEXT;
  }

} //FreeTextImpl
