/**
 * generated by Xtext 2.10.0
 */
package ingraph.report.feature.impl;

import org.eclipse.emf.ecore.EClass;

import ingraph.report.feature.FeaturePackage;
import ingraph.report.feature.InOrderTo;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>In Order To</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InOrderToImpl extends NarrativeElementImpl implements InOrderTo
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InOrderToImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FeaturePackage.Literals.IN_ORDER_TO;
  }

} //InOrderToImpl
